In [45]:
import pandas as pd

In [47]:
df = pd.read_csv(r"BsraHull/data/cb0p7.csv", index_col=0);
#df.dropna(axis=1, how='all',inplace =True)
df

           0  0.075   0.25    0.5   0.75      1   1.25    1.5    SAR
0      0.000  0.000  0.000  0.000  0.000  0.000  0.020  0.051  0.000
0.5    0.009  0.049  0.072  0.081  0.086  0.094  0.119  0.176  0.076
1      0.026  0.110  0.158  0.177  0.184  0.194  0.229  0.299  0.165
1.5    0.054  0.183  0.252  0.281  0.294  0.310  0.350  0.421  0.266
2      0.100  0.266  0.350  0.389  0.407  0.430  0.472  0.536  0.370
3      0.239  0.450  0.550  0.599  0.627  0.655  0.689  0.734  0.579
4      0.437  0.625  0.724  0.778  0.802  0.827  0.851  0.877  0.755
5      0.646  0.783  0.856  0.904  0.920  0.935  0.948  0.961  0.882
6      0.830  0.896  0.942  0.971  0.980  0.985  0.990  0.992  0.958
7      0.939  0.970  0.984  0.994  0.998  1.000  1.000  1.000  0.990
8      0.998  1.000  1.000  1.000  1.000  1.000  1.000  1.000  0.999
9      1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000
10     1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000
11     1.000  0.997  0.999  1.000  1.000  1.000  1.000  1.000  0.999
12     0.961  0.978  0.989  1.000  1.000  1.000  1.000  1.000  0.994
13     0.855  0.917  0.958  0.993  1.000  1.000  1.000  1.000  0.977
14     0.705  0.815  0.887  0.957  0.980  0.991  0.998  1.000  0.930
15     0.532  0.675  0.768  0.868  0.927  0.961  0.985  0.990  0.844
16     0.344  0.510  0.605  0.726  0.825  0.897  0.950  0.982  0.713
17     0.186  0.338  0.427  0.533  0.658  0.788  0.881  0.939  0.543
18     0.077  0.192  0.245  0.314  0.425  0.614  0.765  0.854  0.343
18.5   0.042  0.126  0.165  0.207  0.292  0.499  0.680  0.789  0.239
19     0.023  0.070  0.089  0.107  0.164  0.368  0.572  0.704  0.140
19.5   0.014  0.022  0.022  0.024  0.043  0.228  0.444  0.589  0.047
20     0.000  0.000  0.000  0.000  0.000  0.089  0.286  0.438  0.005
MaxBm  0.771  0.926  0.998  1.000  1.000  1.000  1.000  1.000    NaN

In [58]:
off = df[:].drop('SAR', axis=1).drop('MaxBm')
off = off.astype(float)
off.index = off.index.astype(float)
off.columns = off.columns.astype(float)

ValueError: Item wrong length 8 instead of 25.

In [49]:
sar = df['SAR'][:]
sar.drop('MaxBm', inplace=True);
sar.index = sar.index.astype(float);
sar

0.0     0.000
0.5     0.076
1.0     0.165
1.5     0.266
2.0     0.370
3.0     0.579
4.0     0.755
5.0     0.882
6.0     0.958
7.0     0.990
8.0     0.999
9.0     1.000
10.0    1.000
11.0    0.999
12.0    0.994
13.0    0.977
14.0    0.930
15.0    0.844
16.0    0.713
17.0    0.543
18.0    0.343
18.5    0.239
19.0    0.140
19.5    0.047
20.0    0.005
Name: SAR, dtype: float64

In [51]:
maxbm = pd.Series(df.iloc[-1], dtype=float);
maxbm.drop('SAR', inplace= True)
maxbm.index = maxbm.index.astype(float)

In [52]:
maxbm

0.000    0.771
0.075    0.926
0.250    0.998
0.500    1.000
0.750    1.000
1.000    1.000
1.250    1.000
1.500    1.000
Name: MaxBm, dtype: float64

In [53]:

outdic = {
    'maxbm':maxbm,
    'sar':sar,
    'offset':off
}

In [54]:
outdic

{'maxbm': 0.000    0.771
 0.075    0.926
 0.250    0.998
 0.500    1.000
 0.750    1.000
 1.000    1.000
 1.250    1.000
 1.500    1.000
 Name: MaxBm, dtype: float64,
 'offset':       0.000  0.075  0.250  0.500  0.750  1.000  1.250  1.500
 0.0   0.000  0.000  0.000  0.000  0.000  0.000  0.020  0.051
 0.5   0.009  0.049  0.072  0.081  0.086  0.094  0.119  0.176
 1.0   0.026  0.110  0.158  0.177  0.184  0.194  0.229  0.299
 1.5   0.054  0.183  0.252  0.281  0.294  0.310  0.350  0.421
 2.0   0.100  0.266  0.350  0.389  0.407  0.430  0.472  0.536
 3.0   0.239  0.450  0.550  0.599  0.627  0.655  0.689  0.734
 4.0   0.437  0.625  0.724  0.778  0.802  0.827  0.851  0.877
 5.0   0.646  0.783  0.856  0.904  0.920  0.935  0.948  0.961
 6.0   0.830  0.896  0.942  0.971  0.980  0.985  0.990  0.992
 7.0   0.939  0.970  0.984  0.994  0.998  1.000  1.000  1.000
 8.0   0.998  1.000  1.000  1.000  1.000  1.000  1.000  1.000
 9.0   1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000
 10.0  1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000
 11.0  1.000  0.997  0.999  1.000  1.000  1.000  1.000  1.000
 12.0  0.961  0.978  0.989  1.000  1.000  1.000  1.000  1.000
 13.0  0.855  0.917  0.958  0.993  1.000  1.000  1.000  1.000
 14.0  0.705  0.815  0.887  0.957  0.980  0.991  0.998  1.000
 15.0  0.532  0.675  0.768  0.868  0.927  0.961  0.985  0.990
 16.0  0.344  0.510  0.605  0.726  0.825  0.897  0.950  0.982
 17.0  0.186  0.338  0.427  0.533  0.658  0.788  0.881  0.939
 18.0  0.077  0.192  0.245  0.314  0.425  0.614  0.765  0.854
 18.5  0.042  0.126  0.165  0.207  0.292  0.499  0.680  0.789
 19.0  0.023  0.070  0.089  0.107  0.164  0.368  0.572  0.704
 19.5  0.014  0.022  0.022  0.024  0.043  0.228  0.444  0.589
 20.0  0.000  0.000  0.000  0.000  0.000  0.089  0.286  0.438,
 'sar': 0.0     0.000
 0.5     0.076
 1.0     0.165
 1.5     0.266
 2.0     0.370
 3.0     0.579
 4.0     0.755
 5.0     0.882
 6.0     0.958
 7.0     0.990
 8.0     0.999
 9.0     1.000
 10.0    1.000
 11.0    0.999
 12.0    0.994
 13.0    0.977
 14.0    0.930
 15.0    0.844
 16.0    0.713
 17.0    0.543
 18.0    0.343
 18.5    0.239
 19.0    0.140
 19.5    0.047
 20.0    0.005
 Name: SAR, dtype: float64}

In [9]:
import pickle
pickle.dump?

In [57]:
with open('BsraHull/data/cb0p7.bin','wb') as f:
    d = pickle.dump(outdic, f)